export const MOVIES_LIST = [
    "The", "A", "An", "In", "On", "At", "By", "With", "Without", "Under",
    "Over", "Into", "From", "Of", "For", "Against", "Among", "Around", "After", "Before",
    "During", "Behind", "Between", "Beyond", "Across", "Throughout", "Toward", "Towards", "Upon", "Inside",
    "Outside", "Amid", "Amidst", "Despite", "Within", "Above", "Below", "Beside", "Along", "Near",
    "Off", "To", "Alongside", "Amidst", "Despite", "Inside", "Without", "With", "Against", "Along",
    "Behind", "Before", "Over", "From", "Into", "After", "Under", "Upon", "Near", "Beyond",
    "Between", "Across", "Above", "Among", "Amongst", "Alongside", "Inside", "Outside", "Underneath", "Throughout",
    "Toward", "Within", "Last", "First", "New", "Old", "Secret", "Hidden", "Lost", "Dark",
    "Light", "Silent", "Loud", "Final", "Ancient", "Eternal", "Golden", "Infinite", "Mystic", "Quantum",
    "Royal", "Sacred", "Solar", "Stellar", "Titanic", "Ultimate", "Vast", "Whispering", "Zenith", "Majestic",
    "Epic", "Fallen", "Galactic", "Heroic", "Invisible", "Jaded", "Kinetic", "Legendary", "Nebula", "Omniscient",
    "Primal", "Radiant", "Spectral", "Transcendent", "Universal","Avengers", "Singham", "John Wick", "Mission Impossible", "Fast and Furious", 
    "Guardians of the Galaxy", "Spider-Man", "Aquaman", "Deadpool", "The Marvels", 
    "Batman", "Superman", "Wonder Woman", "Black Panther", "Shazam", 
    "Doctor Strange", "Eternals", "Thor", "Jurassic World", "Transformers", 
    "The Matrix", "Avatar", "Dune", "Indiana Jones", "Star Wars", 
    "The Mandalorian", "The Witcher", "Stranger Things", "Squid Game", "The Boys", 
    "The Crown", "Loki", "Secret Invasion", "Echo", "House of the Dragon", 
    "Yellowstone", "Outer Banks", "Ted Lasso", "Wednesday", "The Last of Us", 
    "One Piece", "Attack on Titan", "Demon Slayer", "Jujutsu Kaisen", "Chainsaw Man", 
    "Barbie", "Oppenheimer", "The Flash", "Venom", "Blue Beetle", "X-Men"
  ];